<?php

declare(strict_types=1);

namespace AlephTools\DDD\Common\Model;

use AlephTools\DDD\Common\Infrastructure\Enums\NamedEnum;

/**
 * @method static static AU(string $method = null)
 * @method static static AT(string $method = null)
 * @method static static AZ(string $method = null)
 * @method static static AL(string $method = null)
 * @method static static DZ(string $method = null)
 * @method static static VI(string $method = null)
 * @method static static AS(string $method = null)
 * @method static static AI(string $method = null)
 * @method static static AO(string $method = null)
 * @method static static AD(string $method = null)
 * @method static static AQ(string $method = null)
 * @method static static AG(string $method = null)
 * @method static static AR(string $method = null)
 * @method static static AM(string $method = null)
 * @method static static AW(string $method = null)
 * @method static static AF(string $method = null)
 * @method static static BS(string $method = null)
 * @method static static BD(string $method = null)
 * @method static static BB(string $method = null)
 * @method static static BH(string $method = null)
 * @method static static BZ(string $method = null)
 * @method static static BY(string $method = null)
 * @method static static BE(string $method = null)
 * @method static static BJ(string $method = null)
 * @method static static BM(string $method = null)
 * @method static static BG(string $method = null)
 * @method static static BO(string $method = null)
 * @method static static BQ(string $method = null)
 * @method static static BA(string $method = null)
 * @method static static BW(string $method = null)
 * @method static static BR(string $method = null)
 * @method static static IO(string $method = null)
 * @method static static VG(string $method = null)
 * @method static static BV(string $method = null)
 * @method static static BF(string $method = null)
 * @method static static BI(string $method = null)
 * @method static static BT(string $method = null)
 * @method static static VU(string $method = null)
 * @method static static VA(string $method = null)
 * @method static static GB(string $method = null)
 * @method static static HU(string $method = null)
 * @method static static VE(string $method = null)
 * @method static static TL(string $method = null)
 * @method static static VN(string $method = null)
 * @method static static GA(string $method = null)
 * @method static static HT(string $method = null)
 * @method static static GY(string $method = null)
 * @method static static GM(string $method = null)
 * @method static static GH(string $method = null)
 * @method static static GP(string $method = null)
 * @method static static GT(string $method = null)
 * @method static static GN(string $method = null)
 * @method static static GW(string $method = null)
 * @method static static DE(string $method = null)
 * @method static static GG(string $method = null)
 * @method static static GI(string $method = null)
 * @method static static HN(string $method = null)
 * @method static static HK(string $method = null)
 * @method static static GD(string $method = null)
 * @method static static GL(string $method = null)
 * @method static static GR(string $method = null)
 * @method static static GE(string $method = null)
 * @method static static GU(string $method = null)
 * @method static static DK(string $method = null)
 * @method static static CD(string $method = null)
 * @method static static JE(string $method = null)
 * @method static static DM(string $method = null)
 * @method static static DO(string $method = null)
 * @method static static EG(string $method = null)
 * @method static static ZM(string $method = null)
 * @method static static EH(string $method = null)
 * @method static static ZW(string $method = null)
 * @method static static IL(string $method = null)
 * @method static static IN(string $method = null)
 * @method static static ID(string $method = null)
 * @method static static JO(string $method = null)
 * @method static static IQ(string $method = null)
 * @method static static IR(string $method = null)
 * @method static static IE(string $method = null)
 * @method static static IS(string $method = null)
 * @method static static ES(string $method = null)
 * @method static static IT(string $method = null)
 * @method static static YE(string $method = null)
 * @method static static CV(string $method = null)
 * @method static static KZ(string $method = null)
 * @method static static KY(string $method = null)
 * @method static static KH(string $method = null)
 * @method static static CM(string $method = null)
 * @method static static CA(string $method = null)
 * @method static static QA(string $method = null)
 * @method static static KE(string $method = null)
 * @method static static CY(string $method = null)
 * @method static static KG(string $method = null)
 * @method static static KI(string $method = null)
 * @method static static CN(string $method = null)
 * @method static static KP(string $method = null)
 * @method static static CC(string $method = null)
 * @method static static CO(string $method = null)
 * @method static static KM(string $method = null)
 * @method static static KR(string $method = null)
 * @method static static CR(string $method = null)
 * @method static static CI(string $method = null)
 * @method static static CU(string $method = null)
 * @method static static KW(string $method = null)
 * @method static static CW(string $method = null)
 * @method static static LA(string $method = null)
 * @method static static LV(string $method = null)
 * @method static static LS(string $method = null)
 * @method static static LR(string $method = null)
 * @method static static LB(string $method = null)
 * @method static static LY(string $method = null)
 * @method static static LT(string $method = null)
 * @method static static LI(string $method = null)
 * @method static static LU(string $method = null)
 * @method static static MU(string $method = null)
 * @method static static MR(string $method = null)
 * @method static static MG(string $method = null)
 * @method static static YT(string $method = null)
 * @method static static MO(string $method = null)
 * @method static static MK(string $method = null)
 * @method static static MW(string $method = null)
 * @method static static MY(string $method = null)
 * @method static static ML(string $method = null)
 * @method static static MV(string $method = null)
 * @method static static MT(string $method = null)
 * @method static static MA(string $method = null)
 * @method static static MQ(string $method = null)
 * @method static static MH(string $method = null)
 * @method static static MX(string $method = null)
 * @method static static MZ(string $method = null)
 * @method static static MD(string $method = null)
 * @method static static MC(string $method = null)
 * @method static static MN(string $method = null)
 * @method static static MS(string $method = null)
 * @method static static MM(string $method = null)
 * @method static static NA(string $method = null)
 * @method static static NR(string $method = null)
 * @method static static NP(string $method = null)
 * @method static static NE(string $method = null)
 * @method static static NG(string $method = null)
 * @method static static AN(string $method = null)
 * @method static static NL(string $method = null)
 * @method static static NI(string $method = null)
 * @method static static NU(string $method = null)
 * @method static static NZ(string $method = null)
 * @method static static NC(string $method = null)
 * @method static static NO(string $method = null)
 * @method static static AE(string $method = null)
 * @method static static OM(string $method = null)
 * @method static static NF(string $method = null)
 * @method static static CX(string $method = null)
 * @method static static SH(string $method = null)
 * @method static static HM(string $method = null)
 * @method static static CK(string $method = null)
 * @method static static PN(string $method = null)
 * @method static static TC(string $method = null)
 * @method static static WF(string $method = null)
 * @method static static PK(string $method = null)
 * @method static static PW(string $method = null)
 * @method static static PS(string $method = null)
 * @method static static PA(string $method = null)
 * @method static static PG(string $method = null)
 * @method static static PY(string $method = null)
 * @method static static PE(string $method = null)
 * @method static static PL(string $method = null)
 * @method static static PT(string $method = null)
 * @method static static PR(string $method = null)
 * @method static static CG(string $method = null)
 * @method static static RE(string $method = null)
 * @method static static RU(string $method = null)
 * @method static static RW(string $method = null)
 * @method static static RO(string $method = null)
 * @method static static SV(string $method = null)
 * @method static static WS(string $method = null)
 * @method static static SM(string $method = null)
 * @method static static ST(string $method = null)
 * @method static static SA(string $method = null)
 * @method static static SZ(string $method = null)
 * @method static static MP(string $method = null)
 * @method static static SC(string $method = null)
 * @method static static PM(string $method = null)
 * @method static static SN(string $method = null)
 * @method static static VC(string $method = null)
 * @method static static KN(string $method = null)
 * @method static static LC(string $method = null)
 * @method static static RS(string $method = null)
 * @method static static SG(string $method = null)
 * @method static static SY(string $method = null)
 * @method static static SK(string $method = null)
 * @method static static SI(string $method = null)
 * @method static static SB(string $method = null)
 * @method static static SO(string $method = null)
 * @method static static SD(string $method = null)
 * @method static static SR(string $method = null)
 * @method static static US(string $method = null)
 * @method static static SL(string $method = null)
 * @method static static TJ(string $method = null)
 * @method static static TH(string $method = null)
 * @method static static TW(string $method = null)
 * @method static static TZ(string $method = null)
 * @method static static TG(string $method = null)
 * @method static static TK(string $method = null)
 * @method static static TO(string $method = null)
 * @method static static TT(string $method = null)
 * @method static static TV(string $method = null)
 * @method static static TN(string $method = null)
 * @method static static TM(string $method = null)
 * @method static static TR(string $method = null)
 * @method static static UG(string $method = null)
 * @method static static UZ(string $method = null)
 * @method static static UA(string $method = null)
 * @method static static UY(string $method = null)
 * @method static static FO(string $method = null)
 * @method static static FM(string $method = null)
 * @method static static FJ(string $method = null)
 * @method static static PH(string $method = null)
 * @method static static FI(string $method = null)
 * @method static static FK(string $method = null)
 * @method static static FR(string $method = null)
 * @method static static GF(string $method = null)
 * @method static static PF(string $method = null)
 * @method static static TF(string $method = null)
 * @method static static HR(string $method = null)
 * @method static static CF(string $method = null)
 * @method static static TD(string $method = null)
 * @method static static ME(string $method = null)
 * @method static static CZ(string $method = null)
 * @method static static CL(string $method = null)
 * @method static static CH(string $method = null)
 * @method static static SE(string $method = null)
 * @method static static SJ(string $method = null)
 * @method static static LK(string $method = null)
 * @method static static EC(string $method = null)
 * @method static static GQ(string $method = null)
 * @method static static ER(string $method = null)
 * @method static static EE(string $method = null)
 * @method static static ET(string $method = null)
 * @method static static ZA(string $method = null)
 * @method static static GS(string $method = null)
 * @method static static JM(string $method = null)
 * @method static static JP(string $method = null)
 */
class Country extends NamedEnum
{
    private const AU = ['Australia', 'AUD'];
    private const AT = ['Austria', 'EUR'];
    private const AZ = ['Azerbaijan', 'AZN'];
    private const AL = ['Albania', 'ALL'];
    private const DZ = ['Algeria', 'DZD'];
    private const VI = ['United States Virgin Islands', 'USD'];
    private const AS = ['American Samoa', 'USD'];
    private const AI = ['Anguilla', 'XCD'];
    private const AO = ['Angola', 'AOA'];
    private const AD = ['Andorra', 'EUR'];
    private const AQ = ['Antarctica', 'ZZZ'];
    private const AG = ['Antigua and Barbuda', 'XCD'];
    private const AR = ['Argentina', 'ARS'];
    private const AM = ['Armenia', 'AMD'];
    private const AW = ['Aruba', 'AWG'];
    private const AF = ['Afghanistan', 'AFN'];
    private const BS = ['Bahamas', 'BSD'];
    private const BD = ['Bangladesh', 'BDT'];
    private const BB = ['Barbados', 'BBD'];
    private const BH = ['Bahrain', 'BHD'];
    private const BZ = ['Belize', 'BZD'];
    private const BY = ['Belarus', 'BYN'];
    private const BE = ['Belgium', 'EUR'];
    private const BJ = ['Benin', 'XOF'];
    private const BM = ['Bermuda', 'BMD'];
    private const BG = ['Bulgaria', 'BGN'];
    private const BO = ['Bolivia', 'BOB'];
    private const BQ = ['Caribbean Netherlands', 'EUR'];
    private const BA = ['Bosnia and Herzegovina', 'BAM'];
    private const BW = ['Botswana', 'BWP'];
    private const BR = ['Brazil', 'BRL'];
    private const IO = ['British Indian Ocean Territory', 'USD'];
    private const VG = ['British Virgin Islands', 'USD'];
    private const BN = ['Brunei Darussalam', 'BND'];
    private const BV = ['Bouvet Island', 'NOK'];
    private const BF = ['Burkina Faso', 'XOF'];
    private const BI = ['Burundi', 'BIF'];
    private const BT = ['Bhutan', 'BTN'];
    private const VU = ['Vanuatu', 'VUV'];
    private const VA = ['Vatican', 'EUR'];
    private const GB = ['Great Britain', 'GBP'];
    private const HU = ['Hungary', 'HUF'];
    private const VE = ['Venezuela', 'VEF'];
    private const TL = ['East Timor', 'USD'];
    private const VN = ['Vietnam', 'VND'];
    private const GA = ['Gabon', 'XAF'];
    private const HT = ['Haiti', 'HTG'];
    private const GY = ['Guyana', 'GYD'];
    private const GM = ['Gambia', 'GMD'];
    private const GH = ['Ghana', 'GHS'];
    private const GP = ['Guadeloupe', 'EUR'];
    private const GT = ['Guatemala', 'GTQ'];
    private const GN = ['Guinea', 'GNF'];
    private const GW = 'Guinea-Bissau';
    private const DE = ['Germany', 'EUR'];
    private const GG = ['Guernsey', 'GBP'];
    private const GI = ['Gibraltar', 'GIP'];
    private const HN = ['Honduras', 'HNL'];
    private const HK = ['Hong Kong', 'HKD'];
    private const GD = ['Grenada', 'XCD'];
    private const GL = ['Greenland', 'DKK'];
    private const GR = ['Greece', 'EUR'];
    private const GE = ['Georgia', 'GEL'];
    private const GU = ['Guam', 'USD'];
    private const DK = ['Denmark', 'DKK'];
    private const CD = ['Democratic Republic of the Congo', 'CDF'];
    private const JE = ['Jersey', 'GBP'];
    private const DJ = ['Djibouti', 'DJF'];
    private const DM = ['Dominica', 'XCD'];
    private const DO = ['Dominican Republic', 'DOP'];
    private const EG = ['Egypt', 'EGP'];
    private const ZM = ['Zambia', 'ZMW'];
    private const EH = ['Western Sahara', 'MAD'];
    private const ZW = ['Zimbabwe', 'ZWL'];
    private const IL = ['Israel', 'ILS'];
    private const IN = ['India', 'INR'];
    private const ID = ['Indonesia', 'IDR'];
    private const JO = ['Jordan', 'JOD'];
    private const IQ = ['Iraq', 'IQD'];
    private const IR = ['Iran', 'IRR'];
    private const IE = ['Ireland', 'EUR'];
    private const IS = ['Iceland', 'ISK'];
    private const ES = ['Spain', 'EUR'];
    private const IT = ['Italy', 'EUR'];
    private const YE = ['Yemen', 'YER'];
    private const CV = ['Cabo Verde', 'CVE'];
    private const KZ = ['Kazakhstan', 'KZT'];
    private const KY = ['Cayman Islands', 'KYD'];
    private const KH = ['Cambodia', 'KHR'];
    private const CM = ['Cameroon', 'XAF'];
    private const CA = ['Canada', 'CAD'];
    private const QA = ['Qatar', 'QAR'];
    private const KE = ['Kenya', 'KES'];
    private const CY = ['Cyprus', 'EUR'];
    private const KG = ['Kyrgyzstan', 'KGS'];
    private const KI = ['Kiribati', 'AUD'];
    private const CN = ['China', 'CNY'];
    private const KP = ['North Korea', 'KPW'];
    private const CC = ['Cocos (Keeling) Islands', 'AUD'];
    private const CO = ['Colombia', 'COP'];
    private const KM = ['Comoros', 'KMF'];
    private const KR = ['Korea', 'KRW'];
    private const CR = ['Costa Rica', 'CRC'];
    private const CI = ['Cote d\'Ivoire (Ivory Coast)', 'XOF'];
    private const CU = ['Cuba', 'CUP'];
    private const KW = ['Kuwait', 'KWD'];
    private const CW = ['Curacao', 'ANG'];
    private const LA = ['Laos', 'LAK'];
    private const LV = ['Latvia', 'EUR'];
    private const LS = ['Lesotho', 'LSL'];
    private const LR = ['Liberia', 'LRD'];
    private const LB = ['Lebanon', 'LBP'];
    private const LY = ['Libya', 'LYD'];
    private const LT = ['Lithuania', 'EUR'];
    private const LI = ['Liechtenstein', 'CHF'];
    private const LU = ['Luxembourg', 'EUR'];
    private const MU = ['Mauritius', 'MUR'];
    private const MR = ['Mauritania', 'MRU'];
    private const MG = ['Madagascar', 'MGA'];
    private const YT = ['Mayotte', 'EUR'];
    private const MO = ['Macau', 'MOP'];
    private const MK = ['Macedonia', 'MKD'];
    private const MW = ['Malawi', 'MWK'];
    private const MY = ['Malaysia', 'MYR'];
    private const ML = ['Mali', 'XOF'];
    private const MV = ['Maldives', 'MVR'];
    private const MT = ['Malta', 'EUR'];
    private const MA = ['Morocco', 'MAD'];
    private const MQ = ['Martinique', 'EUR'];
    private const MH = ['Marshall Islands', 'USD'];
    private const MX = ['Mexico', 'MXN'];
    private const MZ = ['Mozambique', 'MZN'];
    private const MD = ['Moldova', 'MDL'];
    private const MC = ['Monaco', 'EUR'];
    private const MN = ['Mongolia', 'MNT'];
    private const MS = ['Montserrat', 'XCD'];
    private const MM = ['Myanmar (Burma)', 'MMK'];
    private const NA = ['Namibia', 'NAD'];
    private const NR = ['Nauru', 'AUD'];
    private const NP = ['Nepal', 'NPR'];
    private const NE = ['Niger', 'XOF'];
    private const NG = ['Nigeria', 'NGN'];
    private const AN = ['Netherlands Antilles', 'ANG'];
    private const NL = ['Netherlands', 'EUR'];
    private const NI = ['Nicaragua', 'NIO'];
    private const NU = ['Niue', 'NZD'];
    private const NZ = ['Zealand', 'NZD'];
    private const NC = ['Caledonia', 'XPF'];
    private const NO = ['Norway', 'NOK'];
    private const AE = ['United Arab Emirates', 'AED'];
    private const OM = ['Oman', 'OMR'];
    private const NF = ['Norfolk Island', 'AUD'];
    private const CX = ['Christmas Island', 'AUD'];
    private const SH = ['Saint Helena', 'SHP'];
    private const HM = ['Heard Island and McDonald Islands', 'AUD'];
    private const CK = ['Cook Islands', 'NZD'];
    private const PN = ['Pitcairn Islands', 'NZD'];
    private const TC = ['The Turks and Caicos Islands', 'USD'];
    private const WF = ['Wallis and Futuna', 'XPF'];
    private const PK = ['Pakistan', 'PKR'];
    private const PW = ['Palau', 'USD'];
    private const PS = ['Palestinian Territories', 'ZZZ'];
    private const PA = ['Panama', 'PAB'];
    private const PG = ['Papua New Guinea', 'PGK'];
    private const PY = ['Paraguay', 'PYG'];
    private const PE = ['Peru', 'PEN'];
    private const PL = ['Poland', 'PLN'];
    private const PT = ['Portugal', 'EUR'];
    private const PR = ['Puerto Rico', 'USD'];
    private const CG = ['Republic of the Congo', 'CDF'];
    private const RE = ['Reunion', 'EUR'];
    private const RU = ['Russia', 'RUB'];
    private const RW = ['Rwanda', 'RWF'];
    private const RO = ['Romania', 'RON'];
    private const SV = ['El Salvador', 'SVC'];
    private const WS = ['Samoa', 'WST'];
    private const SM = ['San Marino', 'EUR'];
    private const ST = ['Sao Tome and Principe', 'STN'];
    private const SA = ['Saudi Arabia', 'SAR'];
    private const SZ = ['Swaziland', 'SZL'];
    private const MP = ['Northern Mariana Islands', 'USD'];
    private const SC = ['Seychelles', 'SCR'];
    private const PM = ['Saint-Pierre and Miquelon', 'EUR'];
    private const SN = ['Senegal', 'XOF'];
    private const VC = ['Saint Vincent and the Grenadines', 'XCD'];
    private const KN = ['Saint Kitts and Nevis', 'XCD'];
    private const LC = ['Saint Lucia', 'XCD'];
    private const RS = ['Serbia', 'RSD'];
    private const SG = ['Singapore', 'SGD'];
    private const SY = ['Syria', 'SYP'];
    private const SK = ['Slovakia', 'EUR'];
    private const SI = ['Slovenia', 'EUR'];
    private const SB = ['Solomon Islands', 'SBD'];
    private const SO = ['Somalia', 'SOS'];
    private const SD = ['Sudan', 'SDG'];
    private const SR = ['Suriname', 'SRD'];
    private const US = ['USA', 'USD'];
    private const SL = ['Sierra Leone', 'SLE'];
    private const TJ = ['Tajikistan', 'TJS'];
    private const TH = ['Thailand', 'THB'];
    private const TW = ['Taiwan (Taipei)', 'TWD'];
    private const TZ = ['Tanzania', 'TZS'];
    private const TG = ['Togo', 'XOF'];
    private const TK = ['Tokelau', 'NZD'];
    private const TO = ['Tonga', 'TOP'];
    private const TT = ['Trinidad and Tobago', 'TTD'];
    private const TV = ['Tuvalu', 'AUD'];
    private const TN = ['Tunisia', 'TND'];
    private const TM = ['Turkmenistan', 'TMT'];
    private const TR = ['Turkey', 'TRY'];
    private const UG = ['Uganda', 'UGX'];
    private const UZ = ['Uzbekistan', 'UZS'];
    private const UA = ['Ukraine', 'UAH'];
    private const UY = ['Uruguay', 'UYI'];
    private const FO = ['Faroe Islands', 'DKK'];
    private const FM = ['Federated States of Micronesia', 'USD'];
    private const FJ = ['Fiji', 'FJD'];
    private const PH = ['Philippines', 'PHP'];
    private const FI = ['Finland', 'EUR'];
    private const FK = ['Falkland Islands (Malvinas)', 'FKP'];
    private const FR = ['France', 'EUR'];
    private const GF = ['French Guiana', 'EUR'];
    private const PF = ['French Polynesia', 'XPF'];
    private const TF = ['French Southern Territories', 'EUR'];
    private const HR = ['Croatia', 'EUR'];
    private const CF = ['Central African Republic', 'XAF'];
    private const TD = ['Chad', 'XAF'];
    private const ME = ['Montenegro', 'EUR'];
    private const CZ = ['Czechia', 'CZK'];
    private const CL = ['Chile', 'CLP'];
    private const CH = ['Switzerland', 'CHE'];
    private const SE = ['Sweden', 'SEK'];
    private const SJ = ['Svalbard and Jan Mayen', 'NOK'];
    private const LK = ['Sri Lanka', 'LKR'];
    private const EC = ['Ecuador', 'USD'];
    private const GQ = ['Equatorial Guinea', 'XAF'];
    private const ER = ['Eritrea', 'ERN'];
    private const EE = ['Estonia', 'EUR'];
    private const ET = ['Ethiopia', 'ETB'];
    private const ZA = ['Republic of South Africa', 'ZAR'];
    private const GS = ['South Georgia and the South Sandwich Islands', 'ZZZ'];
    private const JM = ['Jamaica', 'JMD'];
    private const JP = ['Japan', 'JPY'];

    private string $currency;

    protected function __construct(string $name, string $currency)
    {
        parent::__construct($name);
        $this->currency = $currency;
    }

    public function getCurrency(): Currency
    {
        return Currency::from($this->currency);
    }
}
