<?php

declare(strict_types=1);

namespace AlephTools\DDD\Common\Model;

use AlephTools\DDD\Common\Infrastructure\Enums\NamedEnum;

/**
 * @method static static AU(string $method = null)
 * @method static static AT(string $method = null)
 * @method static static AZ(string $method = null)
 * @method static static AL(string $method = null)
 * @method static static DZ(string $method = null)
 * @method static static VI(string $method = null)
 * @method static static AS(string $method = null)
 * @method static static AI(string $method = null)
 * @method static static AO(string $method = null)
 * @method static static AD(string $method = null)
 * @method static static AQ(string $method = null)
 * @method static static AG(string $method = null)
 * @method static static AR(string $method = null)
 * @method static static AM(string $method = null)
 * @method static static AW(string $method = null)
 * @method static static AF(string $method = null)
 * @method static static BS(string $method = null)
 * @method static static BD(string $method = null)
 * @method static static BB(string $method = null)
 * @method static static BH(string $method = null)
 * @method static static BZ(string $method = null)
 * @method static static BY(string $method = null)
 * @method static static BE(string $method = null)
 * @method static static BJ(string $method = null)
 * @method static static BM(string $method = null)
 * @method static static BG(string $method = null)
 * @method static static BO(string $method = null)
 * @method static static BQ(string $method = null)
 * @method static static BA(string $method = null)
 * @method static static BW(string $method = null)
 * @method static static BR(string $method = null)
 * @method static static IO(string $method = null)
 * @method static static VG(string $method = null)
 * @method static static BV(string $method = null)
 * @method static static BF(string $method = null)
 * @method static static BI(string $method = null)
 * @method static static BT(string $method = null)
 * @method static static VU(string $method = null)
 * @method static static VA(string $method = null)
 * @method static static GB(string $method = null)
 * @method static static HU(string $method = null)
 * @method static static VE(string $method = null)
 * @method static static TL(string $method = null)
 * @method static static VN(string $method = null)
 * @method static static GA(string $method = null)
 * @method static static HT(string $method = null)
 * @method static static GY(string $method = null)
 * @method static static GM(string $method = null)
 * @method static static GH(string $method = null)
 * @method static static GP(string $method = null)
 * @method static static GT(string $method = null)
 * @method static static GN(string $method = null)
 * @method static static GW(string $method = null)
 * @method static static DE(string $method = null)
 * @method static static GG(string $method = null)
 * @method static static GI(string $method = null)
 * @method static static HN(string $method = null)
 * @method static static HK(string $method = null)
 * @method static static GD(string $method = null)
 * @method static static GL(string $method = null)
 * @method static static GR(string $method = null)
 * @method static static GE(string $method = null)
 * @method static static GU(string $method = null)
 * @method static static DK(string $method = null)
 * @method static static CD(string $method = null)
 * @method static static JE(string $method = null)
 * @method static static DM(string $method = null)
 * @method static static DO(string $method = null)
 * @method static static EG(string $method = null)
 * @method static static ZM(string $method = null)
 * @method static static EH(string $method = null)
 * @method static static ZW(string $method = null)
 * @method static static IL(string $method = null)
 * @method static static IN(string $method = null)
 * @method static static ID(string $method = null)
 * @method static static JO(string $method = null)
 * @method static static IQ(string $method = null)
 * @method static static IR(string $method = null)
 * @method static static IE(string $method = null)
 * @method static static IS(string $method = null)
 * @method static static ES(string $method = null)
 * @method static static IT(string $method = null)
 * @method static static YE(string $method = null)
 * @method static static CV(string $method = null)
 * @method static static KZ(string $method = null)
 * @method static static KY(string $method = null)
 * @method static static KH(string $method = null)
 * @method static static CM(string $method = null)
 * @method static static CA(string $method = null)
 * @method static static QA(string $method = null)
 * @method static static KE(string $method = null)
 * @method static static CY(string $method = null)
 * @method static static KG(string $method = null)
 * @method static static KI(string $method = null)
 * @method static static CN(string $method = null)
 * @method static static KP(string $method = null)
 * @method static static CC(string $method = null)
 * @method static static CO(string $method = null)
 * @method static static KM(string $method = null)
 * @method static static KR(string $method = null)
 * @method static static CR(string $method = null)
 * @method static static CI(string $method = null)
 * @method static static CU(string $method = null)
 * @method static static KW(string $method = null)
 * @method static static CW(string $method = null)
 * @method static static LA(string $method = null)
 * @method static static LV(string $method = null)
 * @method static static LS(string $method = null)
 * @method static static LR(string $method = null)
 * @method static static LB(string $method = null)
 * @method static static LY(string $method = null)
 * @method static static LT(string $method = null)
 * @method static static LI(string $method = null)
 * @method static static LU(string $method = null)
 * @method static static MU(string $method = null)
 * @method static static MR(string $method = null)
 * @method static static MG(string $method = null)
 * @method static static YT(string $method = null)
 * @method static static MO(string $method = null)
 * @method static static MK(string $method = null)
 * @method static static MW(string $method = null)
 * @method static static MY(string $method = null)
 * @method static static ML(string $method = null)
 * @method static static MV(string $method = null)
 * @method static static MT(string $method = null)
 * @method static static MA(string $method = null)
 * @method static static MQ(string $method = null)
 * @method static static MH(string $method = null)
 * @method static static MX(string $method = null)
 * @method static static MZ(string $method = null)
 * @method static static MD(string $method = null)
 * @method static static MC(string $method = null)
 * @method static static MN(string $method = null)
 * @method static static MS(string $method = null)
 * @method static static MM(string $method = null)
 * @method static static NA(string $method = null)
 * @method static static NR(string $method = null)
 * @method static static NP(string $method = null)
 * @method static static NE(string $method = null)
 * @method static static NG(string $method = null)
 * @method static static AN(string $method = null)
 * @method static static NL(string $method = null)
 * @method static static NI(string $method = null)
 * @method static static NU(string $method = null)
 * @method static static NZ(string $method = null)
 * @method static static NC(string $method = null)
 * @method static static NO(string $method = null)
 * @method static static AE(string $method = null)
 * @method static static OM(string $method = null)
 * @method static static NF(string $method = null)
 * @method static static CX(string $method = null)
 * @method static static SH(string $method = null)
 * @method static static HM(string $method = null)
 * @method static static CK(string $method = null)
 * @method static static PN(string $method = null)
 * @method static static TC(string $method = null)
 * @method static static WF(string $method = null)
 * @method static static PK(string $method = null)
 * @method static static PW(string $method = null)
 * @method static static PS(string $method = null)
 * @method static static PA(string $method = null)
 * @method static static PG(string $method = null)
 * @method static static PY(string $method = null)
 * @method static static PE(string $method = null)
 * @method static static PL(string $method = null)
 * @method static static PT(string $method = null)
 * @method static static PR(string $method = null)
 * @method static static CG(string $method = null)
 * @method static static RE(string $method = null)
 * @method static static RU(string $method = null)
 * @method static static RW(string $method = null)
 * @method static static RO(string $method = null)
 * @method static static SV(string $method = null)
 * @method static static WS(string $method = null)
 * @method static static SM(string $method = null)
 * @method static static ST(string $method = null)
 * @method static static SA(string $method = null)
 * @method static static SZ(string $method = null)
 * @method static static MP(string $method = null)
 * @method static static SC(string $method = null)
 * @method static static PM(string $method = null)
 * @method static static SN(string $method = null)
 * @method static static VC(string $method = null)
 * @method static static KN(string $method = null)
 * @method static static LC(string $method = null)
 * @method static static RS(string $method = null)
 * @method static static SG(string $method = null)
 * @method static static SY(string $method = null)
 * @method static static SK(string $method = null)
 * @method static static SI(string $method = null)
 * @method static static SB(string $method = null)
 * @method static static SO(string $method = null)
 * @method static static SD(string $method = null)
 * @method static static SR(string $method = null)
 * @method static static US(string $method = null)
 * @method static static SL(string $method = null)
 * @method static static TJ(string $method = null)
 * @method static static TH(string $method = null)
 * @method static static TW(string $method = null)
 * @method static static TZ(string $method = null)
 * @method static static TG(string $method = null)
 * @method static static TK(string $method = null)
 * @method static static TO(string $method = null)
 * @method static static TT(string $method = null)
 * @method static static TV(string $method = null)
 * @method static static TN(string $method = null)
 * @method static static TM(string $method = null)
 * @method static static TR(string $method = null)
 * @method static static UG(string $method = null)
 * @method static static UZ(string $method = null)
 * @method static static UA(string $method = null)
 * @method static static UY(string $method = null)
 * @method static static FO(string $method = null)
 * @method static static FM(string $method = null)
 * @method static static FJ(string $method = null)
 * @method static static PH(string $method = null)
 * @method static static FI(string $method = null)
 * @method static static FK(string $method = null)
 * @method static static FR(string $method = null)
 * @method static static GF(string $method = null)
 * @method static static PF(string $method = null)
 * @method static static TF(string $method = null)
 * @method static static HR(string $method = null)
 * @method static static CF(string $method = null)
 * @method static static TD(string $method = null)
 * @method static static ME(string $method = null)
 * @method static static CZ(string $method = null)
 * @method static static CL(string $method = null)
 * @method static static CH(string $method = null)
 * @method static static SE(string $method = null)
 * @method static static SJ(string $method = null)
 * @method static static LK(string $method = null)
 * @method static static EC(string $method = null)
 * @method static static GQ(string $method = null)
 * @method static static ER(string $method = null)
 * @method static static EE(string $method = null)
 * @method static static ET(string $method = null)
 * @method static static ZA(string $method = null)
 * @method static static GS(string $method = null)
 * @method static static JM(string $method = null)
 * @method static static JP(string $method = null)
 */
class Country extends NamedEnum
{
    private const AU = 'Australia';
    private const AT = 'Austria';
    private const AZ = 'Azerbaijan';
    private const AL = 'Albania';
    private const DZ = 'Algeria';
    private const VI = 'United States Virgin Islands';
    private const AS = 'American Samoa';
    private const AI = 'Anguilla';
    private const AO = 'Angola';
    private const AD = 'Andorra';
    private const AQ = 'Antarctica';
    private const AG = 'Antigua and Barbuda';
    private const AR = 'Argentina';
    private const AM = 'Armenia';
    private const AW = 'Aruba';
    private const AF = 'Afghanistan';
    private const BS = 'Bahamas';
    private const BD = 'Bangladesh';
    private const BB = 'Barbados';
    private const BH = 'Bahrain';
    private const BZ = 'Belize';
    private const BY = 'Belarus';
    private const BE = 'Belgium';
    private const BJ = 'Benin';
    private const BM = 'Bermuda';
    private const BG = 'Bulgaria';
    private const BO = 'Bolivia';
    private const BQ = 'Caribbean Netherlands';
    private const BA = 'Bosnia and Herzegovina';
    private const BW = 'Botswana';
    private const BR = 'Brazil';
    private const IO = 'British Indian Ocean Territory';
    private const VG = 'British Virgin Islands';
    private const BN = 'Brunei Darussalam';
    private const BV = 'Bouvet Island';
    private const BF = 'Burkina Faso';
    private const BI = 'Burundi';
    private const BT = 'Bhutan';
    private const VU = 'Vanuatu';
    private const VA = 'Vatican';
    private const GB = 'Great Britain';
    private const HU = 'Hungary';
    private const VE = 'Venezuela';
    private const TL = 'East Timor';
    private const VN = 'Vietnam';
    private const GA = 'Gabon';
    private const HT = 'Haiti';
    private const GY = 'Guyana';
    private const GM = 'Gambia';
    private const GH = 'Ghana';
    private const GP = 'Guadeloupe';
    private const GT = 'Guatemala';
    private const GN = 'Guinea';
    private const GW = 'Guinea-Bissau';
    private const DE = 'Germany';
    private const GG = 'Guernsey';
    private const GI = 'Gibraltar';
    private const HN = 'Honduras';
    private const HK = 'Hong Kong';
    private const GD = 'Grenada';
    private const GL = 'Greenland';
    private const GR = 'Greece';
    private const GE = 'Georgia';
    private const GU = 'Guam';
    private const DK = 'Denmark';
    private const CD = 'Democratic Republic of the Congo';
    private const JE = 'Jersey';
    private const DJ = 'Djibouti';
    private const DM = 'Dominica';
    private const DO = 'Dominican Republic';
    private const EG = 'Egypt';
    private const ZM = 'Zambia';
    private const EH = 'Western Sahara';
    private const ZW = 'Zimbabwe';
    private const IL = 'Israel';
    private const IN = 'India';
    private const ID = 'Indonesia';
    private const JO = 'Jordan';
    private const IQ = 'Iraq';
    private const IR = 'Iran';
    private const IE = 'Ireland';
    private const IS = 'Iceland';
    private const ES = 'Spain';
    private const IT = 'Italy';
    private const YE = 'Yemen';
    private const CV = 'Cape Verde';
    private const KZ = 'Kazakhstan';
    private const KY = 'Cayman Islands';
    private const KH = 'Cambodia';
    private const CM = 'Cameroon';
    private const CA = 'Canada';
    private const QA = 'Quatar';
    private const KE = 'Kenya';
    private const CY = 'Cyprus';
    private const KG = 'Kyrgyzstan';
    private const KI = 'Kiribati';
    private const CN = 'China';
    private const KP = 'North Korea';
    private const CC = 'Cocos (Keeling) Islands';
    private const CO = 'Colombia';
    private const KM = 'Comoros';
    private const KR = 'Korea';
    private const CR = 'Costa Rica';
    private const CI = 'Cote d\'Ivoire (Ivory Coast)';
    private const CU = 'Cuba';
    private const KW = 'Kuwait';
    private const CW = 'Curacao';
    private const LA = 'Laos';
    private const LV = 'Latvia';
    private const LS = 'Lesotho';
    private const LR = 'Liberia';
    private const LB = 'Lebanon';
    private const LY = 'Libya';
    private const LT = 'Lithuania';
    private const LI = 'Liechtenstein';
    private const LU = 'Luxembourg';
    private const MU = 'Mauritius';
    private const MR = 'Mauritania';
    private const MG = 'Madagascar';
    private const YT = 'Mayotte';
    private const MO = 'Macau';
    private const MK = 'Macedonia';
    private const MW = 'Malawi';
    private const MY = 'Malaysia';
    private const ML = 'Mali';
    private const MV = 'Maldives';
    private const MT = 'Malta';
    private const MA = 'Morocco';
    private const MQ = 'Martinique';
    private const MH = 'Marshall Islands';
    private const MX = 'Mexico';
    private const MZ = 'Mozambique';
    private const MD = 'Moldova';
    private const MC = 'Monaco';
    private const MN = 'Mongolia';
    private const MS = 'Montserrat';
    private const MM = 'Myanmar (Burma)';
    private const NA = 'Namibia';
    private const NR = 'Nauru';
    private const NP = 'Nepal';
    private const NE = 'Niger';
    private const NG = 'Nigeria';
    private const AN = 'Netherlands Antilles';
    private const NL = 'Netherlands';
    private const NI = 'Nicaragua';
    private const NU = 'Niue';
    private const NZ = 'Zealand';
    private const NC = 'Caledonia';
    private const NO = 'Norway';
    private const AE = 'United Arab Emirates';
    private const OM = 'Oman';
    private const NF = 'Norfolk Island';
    private const CX = 'Christmas Island';
    private const SH = 'Saint Helena';
    private const HM = 'Heard Island and McDonald Islands';
    private const CK = 'Cook Islands';
    private const PN = 'Pitcairn Islands';
    private const TC = 'The Turks and Caicos Islands';
    private const WF = 'Wallis and Futuna';
    private const PK = 'Pakistan';
    private const PW = 'Palau';
    private const PS = 'Palestinian Territories';
    private const PA = 'Panama';
    private const PG = 'Papua New Guinea';
    private const PY = 'Paraguay';
    private const PE = 'Peru';
    private const PL = 'Poland';
    private const PT = 'Portugal';
    private const PR = 'Puerto Rico';
    private const CG = 'Republic of the Congo';
    private const RE = 'Reunion';
    private const RU = 'Russia';
    private const RW = 'Rwanda';
    private const RO = 'Romania';
    private const SV = 'El Salvador';
    private const WS = 'Samoa';
    private const SM = 'San Marino';
    private const ST = 'Sao Tome and Principe';
    private const SA = 'Saudi Arabia';
    private const SZ = 'Swaziland';
    private const MP = 'Northern Mariana Islands';
    private const SC = 'Seychelles';
    private const PM = 'Saint-Pierre and Miquelon';
    private const SN = 'Senegal';
    private const VC = 'Saint Vincent and the Grenadines';
    private const KN = 'Saint Kitts and Nevis';
    private const LC = 'Saint Lucia';
    private const RS = 'Serbia';
    private const SG = 'Singapore';
    private const SY = 'Syria';
    private const SK = 'Slovakia';
    private const SI = 'Slovenia';
    private const SB = 'Solomon Islands';
    private const SO = 'Somalia';
    private const SD = 'Sudan';
    private const SR = 'Suriname';
    private const US = 'USA';
    private const SL = 'Sierra Leone';
    private const TJ = 'Tajikistan';
    private const TH = 'Thailand';
    private const TW = 'Taiwan (Taipei)';
    private const TZ = 'Tanzania';
    private const TG = 'Togo';
    private const TK = 'Tokelau';
    private const TO = 'Tonga';
    private const TT = 'Trinidad and Tobago';
    private const TV = 'Tuvalu';
    private const TN = 'Tunisia';
    private const TM = 'Turkmenistan';
    private const TR = 'Turkey';
    private const UG = 'Uganda';
    private const UZ = 'Uzbekistan';
    private const UA = 'Ukraine';
    private const UY = 'Uruguay';
    private const FO = 'Faroe Islands';
    private const FM = 'Federated States of Micronesia';
    private const FJ = 'Fiji';
    private const PH = 'Philippines';
    private const FI = 'Finland';
    private const FK = 'Falkland Islands (Malvinas)';
    private const FR = 'France';
    private const GF = 'French Guiana';
    private const PF = 'French Polynesia';
    private const TF = 'French Southern Territories';
    private const HR = 'Croatia';
    private const CF = 'Central African Republic';
    private const TD = 'Chad';
    private const ME = 'Montenegro';
    private const CZ = 'Czechia';
    private const CL = 'Chile';
    private const CH = 'Switzerland';
    private const SE = 'Sweden';
    private const SJ = 'Svalbard and Jan Mayen';
    private const LK = 'Sri Lanka';
    private const EC = 'Ecuador';
    private const GQ = 'Equatorial Guinea';
    private const ER = 'Eritrea';
    private const EE = 'Estonia';
    private const ET = 'Ethiopia';
    private const ZA = 'Republic of South Africa';
    private const GS = 'South Georgia and the South Sandwich Islands';
    private const JM = 'Jamaica';
    private const JP = 'Japan';
}
